import '../styles/globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import { Navbar } from '@/components';

const roboto = Roboto({ weight: ['100', '300', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Blog',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='es'>
			<body
				className={`container mx-auto bg-neutral-100 dark:bg-neutral-900 dark:text-white ${roboto.className}`}
			>
				<Navbar />
				<div
					id='page-top-spacer'
					className='h-12'
				/>
				{children}
			</body>
		</html>
	);
}
